name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Verifica que este secreto esté configurado correctamente
          password: ${{ secrets.DOCKER_PASSWORD }} # Verifica que este secreto esté configurado correctamente

      - name: Build the Docker image
        run: |
          docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }} .

      - name: Install Anchore CLI
        run: |
          sudo curl -s https://ci-tools.anchore.io/ci-tools.sh | sudo bash

      - name: Scan image with Anchore
        run: |
          docker run -v $(pwd)/anchore-reports:/reports anchore/inline-scan:v0.7.2 --image ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }} --policy_path policies

      - name: Upload scan results
        uses: actions/upload-artifact@v2
        with:
          name: anchore-reports
          path: ./anchore-reports
