name: CI/CD Pipeline

on:
  workflow_dispatch:  # Triggered manually through the Actions interface

jobs:
  build-and-scan:
    runs-on: ubuntu-latest  # Run the job on the latest Ubuntu runner

    steps:
      - uses: actions/checkout@v2  # Checkout code from the GitHub repository

      - uses: docker/setup-buildx-action@v1  # Set up Docker Buildx for multi-platform builds

      - uses: docker/login-action@v2  # Login to DockerHub using secrets
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image (improved)
        run: |
          docker buildx build --platform linux/amd64 -t myapp:${{ github.sha }} .  # Build for amd64 platform

      - name: Instalar la CLI de Anchore (mejorado)
        run: |
          curl -fsSL https://ci-tools.anchore.io/ci-tools.sh | bash -  # Descargar y ejecutar el script de forma segura
        

      - name: Scan image with Anchore (improved)
        run: |
          docker run -v $(pwd)/anchore-reports:/reports anchore/inline-scan:v0.7.2 --image myapp:${{ github.sha }} --policy_path policies  # Scan the built image

      - uses: actions/upload-artifact@v2  # Upload scan results
        with:
          name: anchore-reports  # Artifact name
          path: ./anchore-reports  # Path to reports directory
