name: CI/CD Pipeline

on:
  workflow_dispatch:

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check if image exists in Docker Hub
        id: check-image
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }}"
          if docker pull $IMAGE_NAME; then
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "exists=false" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker Image
        if: env.exists == 'false'
        run: |
          docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }} --push .

      - name: Install Anchore CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          sudo pip3 install anchorecli

      - name: Scan image with Anchore
        run: |
          mkdir -p anchore-reports
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/anchore-reports:/anchore-reports anchore/inline-scan:v0.7.2 ${{ secrets.DOCKER_USERNAME }}/myapp:${{ github.sha }} --policy-path policies

      - name: Upload scan results
        uses: actions/upload-artifact@v2
        with:
          name: anchore-reports
          path: ./anchore-reports
